on: [push]

name: Build Docker Image And Submit Metadata To ReARM

jobs:
  build:
    name: Build And Push Docker Image With Metadata
    runs-on: ubuntu-latest
    steps:
      - name: ReARM Build And Submit Backend Release metadata action
        uses: relizaio/rearm-docker-action@bd898d583896ae9080ca3e12a6bba5ded7d76f04 # experimental
        with:
          registry_username: ${{ secrets.DOCKER_LOGIN }}
          registry_password: ${{ secrets.DOCKER_TOKEN }}
          registry_host: registry.test.relizahub.com
          image_namespace: registry.test.relizahub.com/1ba15cdf-edc1-4c34-abf3-6c886c33ff77-private
          image_name: hello-world
          rearm_api_id: ${{ secrets.REARM_API_ID }}
          rearm_api_key: ${{ secrets.REARM_API_KEY }}
          rearm_api_url: https://dev.rearmhq.com
          path: .
          enable_sbom: 'true'
          source_code_sbom_type: 'none'
